#!/usr/bin/env python

import sys

from rqt_rosparam.rqt_rosparam import RqtRosParam
from rqt_gui.main import Main

plugin = 'rqt_rosparam'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
